### ISSUE TITLE
IE浏览器报错，需编译后再执行

### ISSUE THREAD

**Issue by j78742** [fabioricali/Cryptor#1]

**Comment by fabiorc428** [comment]
Please, tell me in english...

**Comment by j78742** [comment]
Sorry about this. I have tried to use this in my project, and I found that it'll throw error when in IE.
The error may caused by the es6 syntax. And in the beginning of the file 'help.js' , ‘use strict’ is missing.

**Comment by fabiorc428** [comment]
This works only server side.

**Comment by j78742** [comment]
okay, I got it. Thanks for your replying
