### ISSUE TITLE
Change to use createCipheriv instead of createCipher

### ISSUE THREAD

**Issue by hongkongkiwi** [fabioricali/Cryptor#2]
Hi there, 

Can you please change the module to use *createCipheriv* instead of _createCipher_? Right now the module produces a warning on the latest node (v9.4.8).

(node:43534) Warning: Use Cipheriv for counter mode of aes-256-ctr

**Comment by alanzhaonys** [comment]
Yes, please change. Thanks

**Comment by fabiorc428** [comment]
Sorry for this delay but I'm very very busy. You can try to fix it then create a PR?...

**Comment by fabiorc428** [comment]
version 3.0.0 now use createCipheriv. Please read [changelog](https://github.com/fabioricali/Cryptor/blob/master/CHANGELOG.md) for details
